config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: "registrations" }
  get 'events/index'
  
  root to: "events#index"
  resources :events
  get '/users/:id', to: 'users#show', as: "user"
  post '/users/:user_id/events/:id', to: 'attending_events#create', as: 'create_attending_event'
  get '/users/:id/attended_events', to: 'users#show_attended_events', as: 'show_attended_events'
  delete '/users/:user_id/events/:id', to: 'attending_events#destroy', as: 'destroy_attending_event'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending_event.rb
class AttendingEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attending_events
  has_many :attendees, through: :attending_events, source: :user
  scope :future, -> { where('date > ?', Time.now) }
  scope :past, -> { where('date < ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, class_name: "Event", foreign_key: "creator_id", dependent: :destroy
  has_many :attending_events, dependent: :destroy
  has_many :attended_events, through: :attending_events, source: :event, foreign_key: 'attendee_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attending_events_controller.rb
class AttendingEventsController < ApplicationController
    def new
        @event = Event.find(params[:id])
    end

    def create
        @event = Event.find(params[:id])
        @event.attendees << current_user
        flash[:notice] = 'You have registered for this event.'
        redirect_to root_path
    end

    def destroy
        @event = Event.find(params[:id])
        @event.attendees.delete(current_user)
        flash[:notice] = 'You have deregistered from the event.'
        redirect_to root_path
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |f|
      if @event.save
        f.html { redirect_to user_path(current_user.id), notice: "Event was successfully created."}
      else
        f.html { render :new }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end


  private

  def event_params
    params.require(:event).permit(:name, :date, :location)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def update_resource(resource, params)
        return super if params['password']&.present?
        resource.update_without_password(params.except('current_password'))
    end

    private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/turbo_devise_user_controller.rb
class TurboDeviseUserController < ApplicationController
    class Responder < ActionController::Responder
       def to_turbo_stream
         controller.render(options.merge(formats: :html))
             rescue ActionView::MissingTemplate => error
         if get?
           raise error
         elsif has_errors? && default_action
           render rendering_options.merge(formats: :html, 
               status: :unprocessable_entity)
         else
           redirect_to navigation_location
         end
       end
     end
   
     self.responder = Responder
     respond_to :html, :turbo_stream
   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
    end

    def show_attended_events
        @attended_events = current_user.attended_events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attending_events_helper.rb
module AttendingEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :date %>
      <%= f.date_select :date %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit "Create Event", class:"button is-primary is-large is-fullwidth" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= link_to 'Cancel', root_path, class:"button is-large is-fullwidth" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h2>Event Edit</h2>
<%= render 'form', event: @event%>

<%= link_to "All Events", events_path%>

app/views/events/index.html.erb
<h1>Events#index</h1>

<% @events.future.each do |event| %>
<%= event.name %><br>
<%= event.date %><br>
<%= event.location %><br>
<div>Created By:<%= event.creator.name %></div><br><br><br>
<%if current_user && event.creator != current_user && !event.attendees.include?(current_user)%>
    <%= button_to "Attend the event", create_attending_event_path(:user_id => current_user.id.to_i, :id => event.id.to_i), method: :post %>
<%elsif current_user && event.creator != current_user && event.attendees.include?(current_user)%>
    <div>You have already registered</div>
    <%= button_to "No longer attending", destroy_attending_event_path(user_id: current_user.id, id: event.id), method: :delete, data: {confirm: "Are you sure?" } %>
<%end%>

<%= link_to "event details", event_path(event.id) %>
<br>
<br>
<%end%>
<br>
<br>
<h2>Past Events</h2>
<% @events.past.each do |event|%>
    <%= event.name %>
    <%= event.date %>
    <%= event.location %>
    <p>Created By: <%=event.creator.name%></p>
    <%= link_to "event details", event_path(event.id) %>
    <br>
<%end%>

app/views/events/new.html.erb
<h2 class="title is-2 is-spaced has-text-centered">Create Event</h2>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1>Event Details</h1>

<p><% @event.name %></p>
<p><% @event.date %></p>
<p><% @event.location %></p>
<p>Created By:<%=@event.creator.name%></p>

<%if current_user && @event.creator != current_user && !@event.attendees.include?(current_user)%>
    <%= button_to "Attend the event", create_attending_event_path(:user_id => current_user.id.to_i, :id => @event.id.to_i), method: :post %>
<%else%>
    <div>You have already registered</div>
<%end%>

<% if current_user && current_user == @event.creator %>
    <%= link_to "Edit Event", edit_event_path(@event.id) %>
    <%= link_to "Delete Event", event_path(@event.id), method: :delete, data: { confirm: "Are you sure?"} %>
<%end%>


<h2>Event Attendees</h2>
<% @event.attendees.each do |a| %>
    <%= a.name %>
<%end%>
<br>
<%= link_to "Go back", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path %>
      <%= link_to current_user.name, edit_user_registration_path%>
      <%= link_to "Your User Details Page", user_path(current_user.id) %>
    <%else%>
      <%=link_to "Sign In", new_user_session_path %>
      <%=link_to "Sign Up", new_user_registration_path %>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User:<%= current_user.name%></h1>


<h3>Hosted Events: <%= current_user.created_events.count %></h3>
    <ul>
        <% if current_user.created_events.empty? %>
          <p>User is not hosting</p>
        <% else %>
          <% current_user.created_events.each do |event| %>
            <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
            <li>Event Location:<%=event.location%></li>
            <li>Event Date:<%=event.date%></li>
          <% end %>
        <% end %>
    </ul>

  <h3>Attending Events: <%= current_user.attended_events.count %></h3>
    <ul>
        <% if current_user.attended_events.empty? %>
          <p>User is not attending</p>
        <% else %>
          <p>Future Events</p>
          <% current_user.attended_events.future.each do |event| %>
            <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
            <li>Event Location:<%=event.location%></li>
            <li>Event Date:<%=event.date%></li>
          <% end %>
          <p>Past Events</p>
          <% current_user.attended_events.past.each do |event| %>
            <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
            <li>Event Location:<%=event.location%></li>
            <li>Event Date:<%=event.date%></li>
          <% end %>
        <% end %>
    </ul>

    <div>
      <%= link_to "create new event", new_event_path %>